---
- name: Distribute cluster pubkey + add hosts + labels + OSDs
  hosts: ceph
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../inventory/topologies/{{ ceph_topology }}.yml"
  roles:
    - ceph_cluster
